import numpy as np

scores = np.array([[90, 80, 85],[93, 88, 92], [95, 89, 91]])

print(scores.sum())
print(scores.sum(axis=0))
print(scores.sum(axis=1))
print(scores.mean())
print(scores.mean(axis=0))
print(scores.mean(axis=1))
print(scores.std())
print(scores.std(axis=0))
print(scores.std(axis=1))
print(scores.var())
print(scores.var(axis=0))
print(scores.var(axis=1))
print(scores.max())
print(scores.max(axis=0))
print(scores.max(axis=1))
print(scores.min())
print(scores.min(axis=0))
print(scores.min(axis=1))
print(scores.argmax())
print(scores.argmax(axis=0))
print(scores.argmax(axis=1))
print(scores.argmin())
print(scores.argmin(axis=0))
print(scores.argmin(axis=1))
print(scores.cumsum())
print(scores.cumsum(axis=0))
print(scores.cumsum(axis=1))
print(scores.cumprod())
print(scores.cumprod(axis=0))   
print(scores.cumprod(axis=1))